### ISSUE TITLE
怎么配置datafeed呢？

### ISSUE THREAD

**Issue by zhonglikui** [veighna-global/vnpy_evo#37]
启动vnpy_evo的时候输出
没有配置要使用的数据服务，请修改全局配置中的datafeed相关内容

![image](https://github.com/veighna-global/vnpy_evo/assets/18553671/e86f516e-fb46-4d48-a593-837b88b61165)

![image](https://github.com/veighna-global/vnpy_evo/assets/18553671/6b7850c8-6b7f-46fe-a2eb-55f58843f9f3)

**Comment by veighna-global** [comment]
vnpy_evo支持的交易接口都自带了query_history支持，所以无需额外配置datafeed。

后续我们会提供针对性的量化策略模块，移除datafeed相关的提示信息。
