### ISSUE TITLE
New vnpy_evo is not compatible with old apps

### ISSUE THREAD

**Issue by linst95** [veighna-global/vnpy_evo#40]
I have installed the latest vnpy_evo and other apps such as ctabacktester and ctastrategy, but it is not running. From the error message, I reckon it is about the UI version is not compatible.

**Steps:**
1. Install python 3.10.11 on windows 11
2. Install vnpy_evo 
3. Install vnpy_binance, vnpy_ctastrategy, vnpy_ctabacktester and other dependencies
4. run sample code

**Code:**
![image](https://github.com/veighna-global/vnpy_evo/assets/25526144/55440b4c-05a4-4657-829d-c9e3229830d9)

**Error message:**
![image](https://github.com/veighna-global/vnpy_evo/assets/25526144/1433987a-abb6-49ea-a7ae-5cb3e24a460d)

**Comment by linst95** [comment]
all apps were downloaded from github and installed via python setup.py install

**Comment by linst95** [comment]
Ok I have checked the roadmap and it is on todo list:
 implement new quant strategy modules for crypto markets (both backtesting and trading)

**Comment by veighna-global** [comment]
> Ok I have checked the roadmap and it is on todo list: implement new quant strategy modules for crypto markets (both backtesting and trading)

Yes, we will complete this part by v0.3.0, should be released soon.
