### ISSUE TITLE
Please provide your suggestions for new gateway support!

### ISSUE THREAD

**Issue by veighna-global** [veighna-global/vnpy_evo#41]
We have updated the most widely used crypto gateways including:

1. Binance
2. OKX
3. Bybit

After completing the crypto strategy module, we will continue developing new gateways.

Please let us know if you have any suggestions, especially the reason for you to trade on this specific exchange.

**Comment by yinanchen517** [comment]
please add get order book on all gateways if possible. Think that might be good for market maker strategies
