### ISSUE TITLE
这安装也太麻烦了，，，，巨麻烦，，，，我从老版本切换过来，简直了，，，，，，，虽然界面好看一些。

### ISSUE THREAD

**Issue by Edward-WZ** [veighna-global/vnpy_evo#49]
我连mianEngine 源码在哪里能看到，都找不到，，，安装过程中，出现一个  AttributeError: 'LogMonitor' object has no attribute 'NoEditTriggers'. Did you mean: 'editTriggers'?          我也不懂ui的代码，，直接懵了。。。如果没有bug，这个版本的ui体验会很好

**Comment by Edward-WZ** [comment]
我想看一下 现在版本的  几个引擎 代码和老版本的有没有改动，结果根本就找不到在哪里，，，

**Comment by Angryrou** [comment]
`pip install PySide6==6.3.0` 

我也有一样的问题，重新安装一下这个依赖之后就好了

**Comment by ChunYue0** [comment]
这个问题是PySide6版本更新后和vnpy框架下的ui不兼容的问题，跟上面的评论说的一样，用6.3.0版本就可以解决了！

**Comment by veighna-global** [comment]
请使用0.3.0仓库发布后提供的一键安装命令，执行安装即可（推荐使用官方Python环境，不用VeighNa Studio）
