### ISSUE TITLE
EventEngine这个在event下找不到么？event目录是空的

### ISSUE THREAD

**Issue by lionel1993** [veighna-global/vnpy_evo#50]
from vnpy_evo.event import EventEngine

example里的例子好像有问题？

**Comment by ChunYue0** [comment]
如果你是要找EventEngine的话，在vnpy_evo/vnpy_evo/event/__init__.py里面你可以看到
from vnpy.event import *
所以vnpy_evo的EventEngine是借用vnpy框架的，所以直接去vnpy目录下看就可以！

**Comment by 14-b** [comment]
> 如果你是要找EventEngine的话，在vnpy_evo/vnpy_evo/event/**init**.py里面你可以看到 from vnpy.event import * 所以vnpy_evo的EventEngine是借用vnpy框架的，所以直接去vnpy目录下看就可以！

这个版本和vnpy-master相比哪里做了改动吗，还是说和原来是一样的东西

**Comment by veighna-global** [comment]
> > 如果你是要找EventEngine的话，在vnpy_evo/vnpy_evo/event/**init**.py里面你可以看到 from vnpy.event import * 所以vnpy_evo的EventEngine是借用vnpy框架的，所以直接去vnpy目录下看就可以！
> 
> 这个版本和vnpy-master相比哪里做了改动吗，还是说和原来是一样的东西

部分涉及到crypto市场交易规则不同的文件模块进行了调整，其他还是沿用官方vnpy库。
