### ISSUE TITLE
Some solutions to installation issues of vnpy_evo

### ISSUE THREAD

**Issue by ChunYue0** [veighna-global/vnpy_evo#55]
1.If the error is like: 

"AttributeError: 'XXXX' object has no attribute 'NoEditTriggers'. Did you mean: 'editTriggers'?"

Please make sure the version of the PySide6 module is 6.3.0. If its version is not 6.3.0, please reinstall it. You can run the command "pip install PySide6==6.3.0" in the terminal. This error is caused by the incompatibility of the new version PySide6 and vnpy_evo.

2.If the error is like:

"Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PySide6/Qt/lib/QtCore.framework/Versions/A/QtCore (0x11e4f53f8) and /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x13cee52a8). One of the two will be used. Which one is undefined."

Please uninstall all modules that contain the prefix 'PyQt'. And then force reinstall the corresponding PySide6 prefixed module again, if there is still error report. For example, the error is like:

"File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/qframelesswindow/__init__.py", line 20, in <module>
    from PyQt5.QtWidgets import QDialog, QMainWindow
ModuleNotFoundError: No module named 'PyQt5.QtWidgets'"

You can run the commands below to solve:

pip uninstall PyQt-Fluent-Widgets
pip3 install PySide6-Fluent-Widgets --force-reinstall

We don't actually use PyQt related modules, but PySide6 modules, which obfuscates the use of the correct module of PySide6.

**Comment by veighna-global** [comment]
Please use these new install scripts in the repository for quick install.
