### ISSUE TITLE
 启动不了，启动出现这个。"The datafeed to be used is not configured. Please modify the datafeed settings in the global configuration."

### ISSUE THREAD

**Issue by linhertz** [veighna-global/vnpy_evo#57]
PS C:\Trade Testing> python .\run_evo.py

[1;33m📢 Tips:[0m QFluentWidgets Pro is now released. Click [1;96mhttps://qfluentwidgets.com/pages/pro[0m to learn more about it.

The datafeed to be used is not configured. Please modify the datafeed settings in the global configuration.
PS C:\Trade Testing>

启动不了，启动出现这个。

**Comment by 14-b** [comment]
datafeed模块没配置好？
你可以到setting.py看一下

**Comment by veighna-global** [comment]
Evo并不需要使用datafeed，所有历史数据直接从gateway获取，忽略该输出即可。
